DATA LOADING & READING
# Railway Delay Analyzer

In [1]:
import pandas as pd
import numpy as np
from google.colab import files

Upload Dataset

In [2]:
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

print("Dataset loaded successfully!")
print("File Name:", file_name)

Saving railway_delay_analyzer_finaldataset to railway_delay_analyzer_finaldataset
Dataset loaded successfully!
File Name: railway_delay_analyzer_finaldataset

 Read Dataset

In [3]:
df = pd.read_csv(file_name)

Dataset Shape

In [4]:
print("\n" + "=" * 50)
print("DATASET BASIC INFORMATION")
print("=" * 50)

print("Number of Rows    :", df.shape[0])
print("Number of Columns :", df.shape[1])

==================================================
DATASET BASIC INFORMATION
==================================================
Number of Rows    : 50000
Number of Columns : 40

Column Names

In [5]:
print("\n" + "=" * 50)
print("COLUMN NAMES")
print("=" * 50)

for i, column in enumerate(df.columns, start=1):
    print(i, ".", column)

==================================================
COLUMN NAMES
==================================================
1 . date
2 . train_no
3 . train_name
4 . type_code
5 . station_no
6 . station_name
7 . station_full_name
8 . station_zone
9 . station_address
10 . distance_from_origin
11 . arrival_day
12 . arrival_time
13 . departure_day
14 . departure_time
15 . delay
16 . year
17 . month
18 . day_of_week
19 . scheduled_arrival_minutes
20 . scheduled_departure_minutes
21 . delay_status_from_source
22 . delay_over_15_source_units
23 . public_holiday
24 . festival_or_holiday
25 . is_weekend
26 . distance_from_origin_complete_km
27 . route_total_distance_km
28 . train_route
29 . segment_distance_km
30 . scheduled_arrival_time_complete
31 . scheduled_arrival_datetime
32 . actual_arrival_datetime
33 . arrival_delay_minutes
34 . scheduled_vs_actual_arrival_status
35 . weather_condition
36 . temperature_c
37 . rainfall_mm
38 . congestion_index
39 . congestion_level
40 . operational_disruption

First 5 Records

In [6]:
print("\n" + "=" * 50)
print("FIRST 5 RECORDS")
print("=" * 50)

display(df.head())

==================================================
FIRST 5 RECORDS
==================================================

,date,train_no,train_name,type_code,station_no,station_name,station_full_name,station_zone,station_address,distance_from_origin,...,scheduled_arrival_datetime,actual_arrival_datetime,arrival_delay_minutes,scheduled_vs_actual_arrival_status,weather_condition,temperature_c,rainfall_mm,congestion_index,congestion_level,operational_disruption
0,2025-02-12,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-12 09:37,2025-02-12 09:37,0.0,Early/on-time,Cloudy,16.3,0.0,0.27,Low,Normal operations
1,2025-02-13,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-13 09:37,2025-02-13 09:37,0.0,Early/on-time,Clear,15.8,0.0,0.27,Low,Normal operations
2,2025-02-22,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-22 09:37,2025-02-22 09:37,0.0,Early/on-time,Cool & Clear,16.6,0.0,0.37,Moderate,Normal operations
3,2025-02-23,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-23 09:37,2025-02-23 09:37,0.0,Early/on-time,Cloudy,21.8,0.0,0.37,Moderate,Normal operations
4,2025-02-24,961,VALLEY QUEEN SPL,EXP-TRAINS,1,MJ,MARWAR JN,NWR,"Pali, Rajasthan, India",0.0,...,2025-02-24 09:37,2025-02-24 09:37,0.0,Early/on-time,Cloudy,19.7,0.0,0.27,Low,Normal operations

Last 5 Records

In [7]:
print("\n" + "=" * 50)
print("LAST 5 RECORDS")
print("=" * 50)

display(df.tail())

==================================================
LAST 5 RECORDS
==================================================

,date,train_no,train_name,type_code,station_no,station_name,station_full_name,station_zone,station_address,distance_from_origin,...,scheduled_arrival_datetime,actual_arrival_datetime,arrival_delay_minutes,scheduled_vs_actual_arrival_status,weather_condition,temperature_c,rainfall_mm,congestion_index,congestion_level,operational_disruption
49995,2025-02-23,1212,NK BD SPL,PASS-TRAINS,8,PC,PACHORA JN,CR,"Pachora, Maharashtra, India",185.0,...,2025-02-23 23:36,2025-02-23 23:53,17.0,Moderate delay (16-60 min),Cloudy,21.3,0.0,0.415,Moderate,Minor operational delay
49996,2025-02-24,1212,NK BD SPL,PASS-TRAINS,8,PC,PACHORA JN,CR,"Pachora, Maharashtra, India",185.0,...,2025-02-24 23:36,2025-02-25 00:19,43.0,Moderate delay (16-60 min),Cloudy,23.4,0.0,0.380,Moderate,Minor operational delay
49997,2025-02-25,1212,NK BD SPL,PASS-TRAINS,8,PC,PACHORA JN,CR,"Pachora, Maharashtra, India",185.0,...,2025-02-25 23:36,2025-02-26 00:24,48.0,Moderate delay (16-60 min),Clear,24.7,0.0,0.392,Moderate,Minor operational delay
49998,2025-02-26,1212,NK BD SPL,PASS-TRAINS,8,PC,PACHORA JN,CR,"Pachora, Maharashtra, India",185.0,...,2025-02-26 23:36,2025-02-26 23:57,21.0,Moderate delay (16-60 min),Cloudy,22.4,0.0,0.545,Moderate,Minor operational delay
49999,2025-02-27,1212,NK BD SPL,PASS-TRAINS,8,PC,PACHORA JN,CR,"Pachora, Maharashtra, India",185.0,...,2025-02-27 23:36,2025-02-28 00:05,29.0,Moderate delay (16-60 min),Cool & Clear,22.0,0.0,0.345,Moderate,Minor operational delay

 Dataset Information

In [8]:
print("\n" + "=" * 50)
print("DATASET INFORMATION")
print("=" * 50)

df.info()

==================================================
DATASET INFORMATION
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 40 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   date                                50000 non-null  object
 1   train_no                            50000 non-null  int64
 2   train_name                          50000 non-null  object
 3   type_code                           50000 non-null  object
 4   station_no                          50000 non-null  int64
 5   station_name                        50000 non-null  object
 6   station_full_name                   50000 non-null  object
 7   station_zone                        50000 non-null  object
 8   station_address                     50000 non-null  object
 9   distance_from_origin                34751 non-null  float64
 10  arrival_day                         34751 non-null  float64
 11  arrival_time                        32183 non-null  object
 12  departure_day                       34751 non-null  float64
 13  departure_time                      33369 non-null  object
 14  delay                               50000 non-null  float64
 15  year                                50000 non-null  int64
 16  month                               50000 non-null  int64
 17  day_of_week                         50000 non-null  object
 18  scheduled_arrival_minutes           32183 non-null  float64
 19  scheduled_departure_minutes         33369 non-null  float64
 20  delay_status_from_source            50000 non-null  object
 21  delay_over_15_source_units          50000 non-null  int64
 22  public_holiday                      50000 non-null  bool
 23  festival_or_holiday                 50000 non-null  object
 24  is_weekend                          50000 non-null  bool
 25  distance_from_origin_complete_km    50000 non-null  float64
 26  route_total_distance_km             50000 non-null  float64
 27  train_route                         50000 non-null  object
 28  segment_distance_km                 50000 non-null  float64
 29  scheduled_arrival_time_complete     50000 non-null  object
 30  scheduled_arrival_datetime          50000 non-null  object
 31  actual_arrival_datetime             50000 non-null  object
 32  arrival_delay_minutes               50000 non-null  float64
 33  scheduled_vs_actual_arrival_status  50000 non-null  object
 34  weather_condition                   50000 non-null  object
 35  temperature_c                       50000 non-null  float64
 36  rainfall_mm                         50000 non-null  float64
 37  congestion_index                    50000 non-null  float64
 38  congestion_level                    50000 non-null  object
 39  operational_disruption              50000 non-null  object
dtypes: bool(2), float64(13), int64(5), object(20)
memory usage: 14.6+ MB

Data Types

In [9]:
print("\n" + "=" * 50)
print("DATA TYPES")
print("=" * 50)

display(df.dtypes.to_frame(name="Data Type"))

==================================================
DATA TYPES
==================================================

                                   Data Type
date                                  object
train_no                               int64
train_name                            object
type_code                             object
station_no                             int64
station_name                          object
station_full_name                     object
station_zone                          object
station_address                       object
distance_from_origin                 float64
arrival_day                          float64
arrival_time                          object
departure_day                        float64
departure_time                        object
delay                                float64
year                                   int64
month                                  int64
day_of_week                           object
scheduled_arrival_minutes            float64
scheduled_departure_minutes          float64
delay_status_from_source              object
delay_over_15_source_units             int64
public_holiday                          bool
festival_or_holiday                   object
is_weekend                              bool
distance_from_origin_complete_km     float64
route_total_distance_km              float64
train_route                           object
segment_distance_km                  float64
scheduled_arrival_time_complete       object
scheduled_arrival_datetime            object
actual_arrival_datetime               object
arrival_delay_minutes                float64
scheduled_vs_actual_arrival_status    object
weather_condition                     object
temperature_c                        float64
rainfall_mm                          float64
congestion_index                     float64
congestion_level                      object
operational_disruption                object

Statistical Summary

In [10]:
print("\n" + "=" * 50)
print("STATISTICAL SUMMARY")
print("=" * 50)

display(df.describe(include="all").T)

==================================================
STATISTICAL SUMMARY
==================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
date,50000,365,2025-05-15,209,NaN,NaN,NaN,NaN,NaN,NaN,NaN
train_no,50000.0,NaN,NaN,NaN,1067.22804,72.314512,961.0,1024.0,1027.0,1139.0,1212.0
train_name,50000,17,Unknown,15249,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type_code,50000,4,EXP-TRAINS,27067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
station_no,50000.0,NaN,NaN,NaN,12.16972,7.51841,1.0,6.0,12.0,18.0,29.0
station_name,50000,140,NK,1628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
station_full_name,50000,139,NASIK ROAD,1628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
station_zone,50000,10,CR,30260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
station_address,50000,127,"Satara, Maharashtra, India",3620,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distance_from_origin,34751.0,NaN,NaN,NaN,333.736238,396.008967,0.0,73.0,181.0,336.0,1647.0
arrival_day,34751.0,NaN,NaN,NaN,1.545653,0.497919,1.0,1.0,2.0,2.0,2.0
arrival_time,32183,123,01:14,724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
departure_day,34751.0,NaN,NaN,NaN,1.545653,0.497919,1.0,1.0,2.0,2.0,2.0
departure_time,33369,128,01:15,724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delay,50000.0,NaN,NaN,NaN,87.4523,129.134588,-76.0,12.0,39.0,112.0,3335.0
year,50000.0,NaN,NaN,NaN,2025.1054,0.307071,2025.0,2025.0,2025.0,2025.0,2026.0
month,50000.0,NaN,NaN,NaN,6.52948,3.385044,1.0,4.0,6.0,9.0,12.0
day_of_week,50000,7,Thursday,8115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scheduled_arrival_minutes,32183.0,NaN,NaN,NaN,644.710593,479.441443,14.0,169.0,635.0,1050.0,1438.0
scheduled_departure_minutes,33369.0,NaN,NaN,NaN,674.88798,482.975176,15.0,170.0,665.0,1082.0,1439.0
delay_status_from_source,50000,3,Delayed,44444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delay_over_15_source_units,50000.0,NaN,NaN,NaN,0.71238,0.452658,0.0,0.0,1.0,1.0,1.0
public_holiday,50000,2,False,47835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
festival_or_holiday,50000,18,No public holiday/festival,47835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_weekend,50000,2,False,34366,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distance_from_origin_complete_km,50000.0,NaN,NaN,NaN,479.9456,502.201941,0.0,120.0,279.0,734.0,2181.0
route_total_distance_km,50000.0,NaN,NaN,NaN,919.494,690.380826,47.0,326.0,790.0,1215.0,2181.0
train_route,50000,21,PUNE JN → SASVAD ROAD → JEJURI → NIRA → LONAND...,7964,NaN,NaN,NaN,NaN,NaN,NaN,NaN
segment_distance_km,50000.0,NaN,NaN,NaN,0.4022,5.210201,0.0,0.0,0.0,0.0,257.0
scheduled_arrival_time_complete,50000,270,04:13,724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scheduled_arrival_datetime,50000,47769,2025-10-26 16:48,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
actual_arrival_datetime,50000,47813,2025-08-10 15:06,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_delay_minutes,50000.0,NaN,NaN,NaN,87.4523,129.134588,-76.0,12.0,39.0,112.0,3335.0
scheduled_vs_actual_arrival_status,50000,4,Major delay (>60 min),19060,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weather_condition,50000,10,Clear,16830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
temperature_c,50000.0,NaN,NaN,NaN,26.232196,5.191622,8.5,22.3,27.3,30.1,41.2
rainfall_mm,50000.0,NaN,NaN,NaN,1.461102,3.985753,0.0,0.0,0.0,0.0,55.5
congestion_index,50000.0,NaN,NaN,NaN,0.564115,0.182929,0.203,0.418,0.522,0.69725,1.0
congestion_level,50000,4,Moderate,26139,NaN,NaN,NaN,NaN,NaN,NaN,NaN
operational_disruption,50000,6,Minor operational delay,15804,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Save Raw Dataset

In [11]:
df.to_csv("stage1_raw_data.csv", index=False)

print("\n" + "=" * 50)
print("STAGE 1 COMPLETED")
print("=" * 50)

print("Output file created: stage1_raw_data.csv")

==================================================
STAGE 1 COMPLETED
==================================================
Output file created: stage1_raw_data.csv